### ISSUE TITLE
Movie Metadata Refresh Crashes

### ISSUE THREAD

**Issue by KingJ** [ZeroQI/Hama.bundle#107]
I updated to d9070e88256403fa06e0f4ba34758b767ab9db67 to start some new development, but when testing a movie refresh the Agent crashes with the following log;
```
2017-01-02 19:17:21,417 - com.plexapp.agents.hama (13668) : INFO (logkit/Info:16) - --- Update Begin -------------------------------------------------------------------------------------------
2017-01-02 19:17:21,417 - com.plexapp.agents.hama (13668) : INFO (logkit/Info:16) - metadata source: 'anidb', id: '6655', Title: 'Macross Frontier: The False Diva', lang: 'en', (True)
2017-01-02 19:17:21,417 - com.plexapp.agents.hama (13668) : INFO (logkit/Info:16) - Finding media path
2017-01-02 19:17:21,418 - com.plexapp.agents.hama (13668) : CRITICAL (core/log_exception:574) - Exception in the update function of agent named 'HamaMovies', called with guid 'com.plexapp.agents.hama://anidb-6655?lang=en' (most recent call last):
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-1bef33a\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\api\agentkit.py", line 1065, in _update
    agent.update(obj, media, lang, **kwargs)
  File "C:\Users\Kingsley\AppData\Local\Plex Media Server\Plug-ins\Hama.bundle\Contents\Code\__init__.py", line 1002, in update
    def update(self, metadata, media, lang, force ): self.Update(metadata, media, lang, force,  True )
  File "C:\Users\Kingsley\AppData\Local\Plex Media Server\Plug-ins\Hama.bundle\Contents\Code\__init__.py", line 725, in Update
    elif not movie and (len(media.seasons)>2 or max(map(int, media.seasons.keys()))>1):  keys = ["tvdbid: %s"  % (WEB_LINK % (TVDB_SERIE_URL  % tvdbid,  tvdbid) )]
  File "C:\Users\Kingsley\AppData\Local\Plex Media Server\Plug-ins\Hama.bundle\Contents\Code\__init__.py", line 738, in anidbTvdbMapping
    for s in media.seasons:  #get first file path
AttributeError: 'MediaTree' object has no attribute 'seasons'
```

Series refresh without issue. 

I think this might have been introduced in 4cdd4d4ede44b090f1cc4858cdc514b7326bf150 but i'm not sure. Either way, for movies the media object doesn't have a seasons attribute so I think [L738](https://github.com/ZeroQI/Hama.bundle/blob/master/Contents/Code/__init__.py#L738) will also need a check to see if the agent is in movie-mode and skip if so?

**Comment by ZeroQI** [comment]
Hi, you are correct, when i coded the custom mapping file, i didn't test for movies since i don't have a movie library
There is still some info that can come from tvdb with the mapping, like the poster since AniDB are lower res and inconsistent unlike thetvdb, hence supporting the mapping file for movies instead of skipping
Thanks for reporting

**Comment by KingJ** [comment]
I updated to 3f8bc902f2c3dd340f84781a6519bd6cd24a3388 and the metadata update gets a bit further but crashes elsewhere;

```
2017-01-03 08:04:33,174 - com.plexapp.agents.hama (15648) : DEBUG (logkit/Debug:13) - Setting season '1' to '2' with offset of '-1'
2017-01-03 08:04:33,174 - com.plexapp.agents.hama (15648) : DEBUG (logkit/Debug:13) - Setting season '0' to '1' with offset of '-1'
2017-01-03 08:04:33,176 - com.plexapp.agents.hama (15648) : DEBUG (logkit/Debug:13) - Setting season '0' to '1' with offset of '-1'
2017-01-03 08:04:33,176 - com.plexapp.agents.hama (15648) : DEBUG (logkit/Debug:13) - Setting season '1' to '2' with offset of '-1'
2017-01-03 08:04:33,176 - com.plexapp.agents.hama (15648) : DEBUG (logkit/Debug:13) - Setting season '0' to '1' with offset of '-1'
2017-01-03 08:04:33,176 - com.plexapp.agents.hama (15648) : DEBUG (logkit/Debug:13) - Setting season '1' to '2' with offset of '-1'
2017-01-03 08:04:33,213 - com.plexapp.agents.hama (15648) : DEBUG (networking/load:161) - Fetching 'http://api.tmdb.org/3/configuration?api_key=7f4a0bd0bd3315bb832e17feda70b5cd' from the HTTP cache
2017-01-03 08:04:33,247 - com.plexapp.agents.hama (15648) : INFO (logkit/Info:16) - using IMDBID url: http://api.tmdb.org/3/find/tt1548563?api_key=7f4a0bd0bd3315bb832e17feda70b5cd&external_source=imdb_id
2017-01-03 08:04:33,283 - com.plexapp.agents.hama (15648) : DEBUG (networking/load:161) - Fetching 'http://api.tmdb.org/3/find/tt1548563?api_key=7f4a0bd0bd3315bb832e17feda70b5cd&external_source=imdb_id' from the HTTP cache
2017-01-03 08:04:33,319 - com.plexapp.agents.hama (15648) : INFO (logkit/Info:16) - url: 'http://image.tmdb.org/t/p/original/5kZhF94osOOxLeThApmTtpV8eJB.jpg', num: '90', filename: 'TMDB/tt1548563.jpg'*
2017-01-03 08:04:33,319 - com.plexapp.agents.hama (15648) : INFO (logkit/Info:16) - url: 'http://image.tmdb.org/t/p/original/1rK17dMPM8IIdQ5n1mFWWKSQzrn.jpg', num: '90', filename: 'TMDB/tt1548563-art.jpg'*
2017-01-03 08:04:33,319 - com.plexapp.agents.hama (15648) : CRITICAL (core/log_exception:574) - Exception in the update function of agent named 'HamaMovies', called with guid 'com.plexapp.agents.hama://anidb-6655?lang=en' (most recent call last):
  File "C:\Program Files (x86)\Plex\Plex Media Server\Resources\Plug-ins-1bef33a\Framework.bundle\Contents\Resources\Versions\2\Python\Framework\api\agentkit.py", line 1065, in _update
    agent.update(obj, media, lang, **kwargs)
  File "C:\Users\Kingsley\AppData\Local\Plex Media Server\Plug-ins\Hama.bundle\Contents\Code\__init__.py", line 1012, in update
    def update(self, metadata, media, lang, force ): self.Update(metadata, media, lang, force,  True )
  File "C:\Users\Kingsley\AppData\Local\Plex Media Server\Plug-ins\Hama.bundle\Contents\Code\__init__.py", line 731, in Update
    elif not movie and (len(media.seasons)>2 or max(map(int, media.seasons.keys()))>1):  keys = ["tvdbid: %s"  % (WEB_LINK % (TVDB_SERIE_URL  % tvdbid,  tvdbid) )]
AttributeError: 'int' object has no attribute 'split'
```
